// src/theme.ts

export const theme = {
  colors: {
    primary: 'bg-primary-600 hover:bg-primary-700 text-white',
    secondary: 'bg-secondary-600 hover:bg-secondary-700 text-white',
    accent: 'bg-accent-500 hover:bg-accent-600 text-white',
    error: 'bg-red-100 border border-red-400 text-red-700',
    success: 'bg-green-100 border border-green-400 text-green-700',
    backgroundGradient: 'bg-gradient-to-br from-primary-50 via-white to-secondary-50',
    glass: 'backdrop-blur-md bg-white/80 border border-white/20 rounded-xl shadow-glass',
    textPrimary: 'text-dark-800',
    textSecondary: 'text-dark-600',
    button: {
      primary: 'btn btn-primary',
      secondary: 'btn btn-secondary',
      accent: 'btn btn-accent',
      outline: 'btn btn-outline',
      icon: 'w-4 h-4',
    },
    spinner: 'w-12 h-12 border-4 border-primary-500 border-t-transparent rounded-full animate-spin',
    badge: 'badge badge-primary',
    overlay: 'fixed inset-0 bg-dark-900/60 backdrop-blur-sm flex items-center justify-center z-50 p-4',
    modal: 'relative bg-white rounded-xl overflow-hidden shadow-xl',
    table: 'w-full',
    tableHeader: 'border-b border-dark-200',
    tableRow: 'border-b border-dark-100 hover:bg-primary-50',
  },
  buttons: {
    upload: 'btn btn-primary',
    toggle: 'btn btn-outline',
    navigation: 'p-2 rounded-full bg-dark-800/30 backdrop-blur-sm border border-white/10 text-white/90 hover:bg-dark-800/50 disabled:opacity-30 disabled:cursor-not-allowed transition-all',
    enlarge: 'p-2 rounded-full bg-white/80 hover:bg-white shadow-md hover:shadow-lg text-dark-800 transition-all duration-200 ease-in-out',
  },
  layout: {
    container: 'min-h-screen text-dark-800 py-8 px-4',
    header: 'text-center space-y-4 mb-8',
    nav: 'flex flex-wrap gap-3 justify-center',
    glassPane: 'glass-card p-4',
    contentPane: 'glass-card p-6 md:p-8',
    table: 'w-full',
    tableHeader: 'border-b border-dark-200',
    tableRow: 'border-b border-dark-100 hover:bg-primary-50',
    badge: 'badge badge-primary',
  },
  text: {
    heading1: 'text-4xl md:text-5xl font-bold font-display bg-clip-text text-transparent bg-gradient-mesh',
    heading2: 'text-2xl font-semibold font-display text-dark-800 flex items-center gap-3',
    heading3: 'text-xl font-semibold font-display text-dark-800',
    paragraph: 'text-lg text-dark-600',
    small: 'text-sm text-dark-500',
    textSecondary: 'text-dark-500',
    modalClose: 'absolute top-2 right-2 p-2 rounded-full bg-white/80 hover:bg-white/100 transition-all',
  },
  animations: {
    fadeIn: {
      initial: { opacity: 0, y: 20 },
      animate: { opacity: 1, y: 0 },
      exit: { opacity: 0, y: -20 },
      transition: { duration: 0.3 },
    },
    slideIn: {
      initial: { opacity: 0, x: -20 },
      animate: { opacity: 1, x: 0 },
      exit: { opacity: 0, x: 20 },
      transition: { duration: 0.3 },
    },
    scaleIn: {
      initial: { opacity: 0, scale: 0.9 },
      animate: { opacity: 1, scale: 1 },
      exit: { opacity: 0, scale: 0.9 },
      transition: { duration: 0.3 },
    },
    spinner: {
      initial: { opacity: 0 },
      animate: { opacity: 1 },
      transition: { duration: 0.5 },
    },
    modalScale: {
      initial: { scale: 0.9, opacity: 0 },
      animate: { scale: 1, opacity: 1 },
      exit: { scale: 0.9, opacity: 0 },
      transition: { duration: 0.3 },
    },
    imageFade: {
      initial: { opacity: 0 },
      animate: { opacity: 1 },
      exit: { opacity: 0 },
      transition: { duration: 0.2 },
    },
  },
};